### ISSUE TITLE
Option to load and merge several configuration files

### ISSUE THREAD

**Issue by ailiev** [buildbarn/bb-storage#17]
It would be useful to have some ability to split the config files. Eg in my setup the storage configuration for all the barn components is the same, while the other settings are mostly different (these are currently command line params).
The actual file format doesn't support features like including separate files. Having a simple feature in the barn config loading to read multiple config files and merge them is one reasonable approach.

**Comment by ailiev** [comment]
The alternative would be for the deployer to do some kind of templating and merging outside the barn process. This is extra work for many users, and also complicated by having most barn components in a bare Docker image without any tools to do the file munging at runtime. (The bare image is fine in itself I'd say)

**Comment by mickael-carl** [comment]
One of the reasons of moving all configuration to json based-file is that you can use [jsonnet](https://jsonnet.org/) to actually template the common part of each components, rather than adding extra logic to merge config files.
I think using jsonnet is simple enough that it can be done by most users of Buildbarn. However we can also provide examples in the [bb-deployment](https://github.com/buildbarn/bb-deployments/) repo to help users get started, and that should solve the usability issue?

**Comment by mickael-carl** [comment]
@ailiev this is now supported out of the box since a56d3a1: you can feed bb-storage (and all other components of Buildbarn) Jsonnet files and it will render them for you, allowing you to merge multiple configuration files without depending on any extra tooling.
bb-deployments will be updated to reflect that change shortly.
