### ISSUE TITLE
bb-storage LocalDirectory cannot navigate to parent directory

### ISSUE THREAD

**Issue by Qinusty** [buildbarn/bb-storage#21]
The validation code for filenames is quite restrictive, including preventing access to parent directories via `..`. This can be seen [here](https://github.com/buildbarn/bb-storage/blob/master/pkg/filesystem/local_directory.go#L20).

This issue is related to https://github.com/buildbarn/bb-remote-execution/issues/18.

**Comment by EdSchouten** [comment]
I consider this specific issue report to be a WONTFIX. This is intentional. bb_worker may run with elevated privileges. Pathname components of `..` are rejected specifically to prevent maliciously crafted build actions from corrupting the system.

In case something like this is needed, it is suggested that consumers of the filesystem API keep references to parent directories themselves and process `..` components manually.

**Comment by EdSchouten** [comment]
To follow up on that: issue https://github.com/buildbarn/bb-remote-execution/issues/18 may be fixed in such a way that it does not require parent directory traversal; LocalBuildDirectory has access to the input root as a whole, so it can do the backtracking there.
