### ISSUE TITLE
BB doesn't output logs

### ISSUE THREAD

**Issue by henryaj** [buildbarn/bb-storage#22]
I'm not seeing much in the way of logging in the bb-storage codebase, and my bb-storage instances aren't outputting any logs at all. Is this intentional?

Happy to open a PR that adds additional logging (perhaps hidden behind a flag). We're attempting to add Bazel remote execution to [thought-machine/please](https://github.com/thought-machine/please), hence the desire to see what buildbarn is doing.

**Comment by mickael-carl** [comment]
Indeed, at this moment bb-storage (and others) are outputting logs only when something actually goes wrong.
Furthermore it has no logging of RPCs, because it would be incredibly spammy. This has somewhat been discussed in [bb-remote-execution](https://github.com/buildbarn/bb-remote-execution/issues/14) already. For those cases, we would like to use Opentracing instead, as introduced in #10, and expand on that PR.
Does that answer your question? Contributions are always welcome of course, especially to expand on tracing as it is currently only enabled in one of the storage backend.
