### ISSUE TITLE
"circular file" means trash can

### ISSUE THREAD

**Issue by abentley** [buildbarn/bb-storage#23]
The most common meaning of "circular file" is a trash can.  This is even what you get when you search "circular file computing" or "circular file storage" on Google.  It would be bad if the file-backed storage was _actually_ deleting its contents.  Different terminology might be better.

**Comment by boseabhishek** [comment]
We are exploring REDIS as backend with Buildbarn because it's more stable and maybe better suited for the purpose.. but yes "circular" maybe a bit misleading??

**Comment by EdSchouten** [comment]
The backend is called 'circular', because it implements a circular buffer: https://en.wikipedia.org/wiki/Circular_buffer

That said, in the long run, CircularBlobAccess will be deprecated. #34 introduces a new storage backend called LocalBlobAccess that should eventually be suitable for both on-disk and in-memory storage needs.

Renaming CircularBlobAccess is pointless, as we should simply work towards kicking it out of the tree. I am therefore closing this issue.
