### ISSUE TITLE
Build without the bytes with circular cache

### ISSUE THREAD

**Issue by moroten** [buildbarn/bb-storage#28]
Using https://blog.bazel.build/2019/05/07/builds-without-bytes.html requires all action outputs to persist during a build. When the circular disk storage gets full, Bazel experiences sporadic failures when blobs are being evicted from the cache.

To solve this, one could rewrite the CAS blobs requested through `Get()` or `FindMissing()`, whenever they get close to being evicted. The threshold can be configured as a percentage threshold.

Action cache requests can also call `FindMissing()` to the CAS for all outputs. As this introduces latency, it should be a configurable option as some users might choose to avoid automatically evicting blobs from their storage.

Any comments or shall I start implementing?

**Comment by EdSchouten** [comment]
CircularBlobAccess implements a circular buffer, meaning it is FIFO-like. Builds without the Bytes requires that storage is LRU-like. This means that CircularBlobAccess is simply unsuitable.

PR #34 adds a new storage backend, LocalBlobAccess, that implements an eviction scheme that should be compatible with Builds without the Bytes. The NewLocalBlobAccess() function has good documentation on how it works under the hood.

The code that is part of #34 will only allow you to use LocalBlobAccess for in-memory storage. The goal is that we work on extending it later on to support on-disk storage, meaning it should become a full replacement for CircularBlobAccess. The goal is that we'll be kicking CircularBlobAccess out of the tree when that happens.

Considering that this issue is about CircularBlobAccess specifically, I think we should close it. We shouldn't attempt to make any improvement in that area. Thanks for reporting it regardless!
